# Grouping and aggregating - Analyzing and exploring your Data

In [60]:
import pandas as pd

In [61]:
dict_cream = {'name': ['Brian Michael','Owen Kelly', 'Candy Pange'], 'weekly intake': [5,6,9], 'favourite car':['Bently','Buggati','Mercedes']}
print(dict_cream)

{'name': ['Brian Michael', 'Owen Kelly', 'Candy Pange'], 'weekly intake': [5, 6, 9], 'favourite car': ['Bently', 'Buggati', 'Mercedes']}

In [62]:
poo = pd.DataFrame(dict_cream)
poo

            name  weekly intake favourite car
0  Brian Michael              5        Bently
1     Owen Kelly              6       Buggati
2    Candy Pange              9      Mercedes

In [63]:
ds = 43
ds

43

In [64]:
df = pd.read_csv('desktop/pandas/survey_results_public.csv')
pd.set_option('display.max_columns', 79)
df

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canada,CAD\tCanadian dollar,NaN,NaN,JavaScript;TypeScript,Rust;TypeScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,macOS,Windows Subsystem for Linux (WSL),Git,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,Daily or almost daily,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
2,3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,5,Data scientist or machine learning specialist;...,20 to 99 employees,I have some influence,NaN,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,32000.0,Yearly,C#;C++;HTML/CSS;JavaScript;Python,C#;C++;HTML/CSS;JavaScript;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Angular.js,Angular;Angular.js,Pandas,.NET,NaN,NaN,Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;S...,Multiple times per day,Yes,Multiple times per day,Neutral,25-34 years old,Man,No,Bisexual,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
3,4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,17,"Developer, full-stack",100 to 499 employees,I have some influence,Other (please specify):,Israel,ILS\tIsraeli new shekel,60000.0,Monthly,C#;JavaScript;SQL;TypeScript,C#;SQL;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,.NET,.NET,NaN,NaN,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Jira Work Management;Trello,Jira Work Management;Trello,Slack;Zoom,Slack;Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,A few times per week,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
4,5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,3,"Developer, front-end;Developer, full-stack;Dev...",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,NaN,NaN,C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;Elixir;F#;Go;JavaScript;Rust;TypeScript,Cloud Firestore;Elasticsearch;Microsoft SQL Se...,Cloud Firestore;Elasticsearch;Firebase Realtim...,Firebase;Microsoft Azure,Firebase;Microsoft Azure,Angular;ASP.NET;ASP.NET Core ;jQuery;Node.js,Angular;ASP.NET Core ;Blazor;Node.js,.NET,.NET;Apache Kafka,npm,Docker;Kubernetes,Notepad++;Visual Studio;Visual Studio Code;Xcode,Rider;Visual Studio;Visual Studio Code,Windows,macOS;Windows,Git;Other (please specify):,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,NaN,Unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73263,73264,I am a developer by profession,"Employed, full-time",Fully remote,Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Udemy,8,5,"Developer, back-end",100 to 499 employees,I have some influence,Visit developer communities like Stack Overflo...,Nigeria,USD\tUnited States dollar,60000.0,Yearly,Bash/Shell;Dart;JavaScript;PHP;Python;SQL;Type...,Bash/Shell;Go;JavaScript;Python;SQL;TypeScript,Elasticsearch;MySQL;PostgreSQL;Redis,MySQL;PostgreSQL;Redis,AWS;DigitalOcean;Google Cloud,AWS;DigitalOcean;Google Cloud,Express;FastAPI;Node.js,Express;FastAPI;Node.js,Flutter,NaN,Docker;Homebrew;Kubernetes;npm,Docker;Homebrew;Kubernetes;npm,IPython/Jupyter;Sublime Text;Vim;Visual Studio...,Sublime Text;Vim;Visual Studio Code,macOS,Linux-based;macOS,Git,Code editor;Command-line,NaN,NaN,Jira Work Management,Jira Work Management,Slack;Zoom,Slack;Zoom,Very favorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely",25-34 years old,Man,No,Straight / Heterosexual,African,None of the above,None of the above,Yes,Independent contributor,5.0,Agree,Disagree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,Never,Never,Never,30-60 minutes a day,Less than 15 minutes a day,Just right,DevOps function;Microservices;Developer portal...,Yes,Yes,Yes,Too long,Easy,NaN
73264,73265,I am a developer by profession,"Employed, full-time",Full in-person,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,Coursera;Udemy;Udacity,6,5,Data scientist or machine learning specialist,I don’t know,I have little or no influence,Other (please specify):;Ask developers I know/...,United States of America,USD\tUnited States dollar,107000.0,Yearly,Bash/Shell;HTML/CSS;JavaScript;Python;SQL,HTML/CSS;JavaScript;Python,Elasticsearch;MongoDB;Oracle;SQLite,Elasticsearch;Neo4j;SQLite,NaN,NaN,FastAPI;Flask;React.js,FastAPI;React.js,Keras;NumPy;Pandas;Scikit-learn;TensorFlow;Tor...,NumPy;Pandas;Torch/PyTorch;Hugging Face Transf...,NaN,NaN,IPython/Jupyter;Notepad++;Spyder;Vim;Visual St...,Notepad++;Spyder;Vim;Visual Studio Code,Linux-based;Windows,Linux-based;Windows,Git,Code editor;Command-line,NaN,NaN,NaN,NaN,Rocketchat,NaN,Unsure,Stack Overflow,Daily or almost daily,Not sure/can't remember,NaN,Neutral,25-34 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,Yes,Independent contributor,6.0,Agree,Agree,Neither agree nor disagree,Disagree,Disagree,Agree,Agree,1-2 times a week,6-10 times a week,10+ times a week,15-30 minutes a day,60-120 minutes a day,Very long,None of these,No,Yes,Yes,Too long,Easy,NaN
73265,73266,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Programming Games;Stac...,Udemy;Codecademy;Pluralsight;edX,42,33,"Developer, full-stack;Developer, desktop or en...",20 to 99 employees,I have a great deal of influence,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,NaN,NaN,HTML/CSS;JavaScript;PHP;Python;SQL,C#;HTML/CSS;JavaScript;PHP;Python;SQL,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;...,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;...,Managed Hosting;Microsoft Azure;VMware,Firebase;Linode;Managed Hosting;Microsoft Azur...,ASP.NET;React.js,ASP.NET;ASP.NET Core ;Blazor;Laravel;Next.js;R...,.NET;Pandas;React Native,.NET;Cordova;Ionic;Pandas;React Native;Xamarin,npm,npm;Unreal Engine,Spyder;Visual Studio;Visual Studio Code,Spyder;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Microsoft Lists,Microsoft Lists,Microsoft Teams;Zoom,Microsoft Teams;Zoom,Very unfavorable,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Less than once per month or monthly,"Yes, somewhat",55-64 years old,Man,No,Straight / Heterosexual,Multiracial,None of the above,None of the above,Yes,Independent contributor,42.0,Disagree,Neither agree nor disagree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Never,Never,Never,30-60 minutes a day,60-120 minutes a day,Just right,None of these,No,No,No,Appropriate in length,Easy,NaN
73266,73267,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;On the job training,NaN,NaN,50,31,"Developer, front-end;Developer, desktop or ent...",10 to 19 employees,I have a great deal of influence,Start a free trial;Visit developer communities...,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,58500.0,Yearly,C#;Delphi;VBA,Delphi,Microsoft SQL Server;MongoDB;Oracle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"RAD Studio (Delphi, C++ Builder);Visual Studio","RAD Studio (Delphi, C++ Builder);Visual Studio",Windows,Windows,SVN,Dedicated version control GUI application,NaN,NaN,NaN,NaN,Zoom,Zoom,Indifferent,Stack Overflow,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not at all",55-64 years old,Man,No,Straight / Heterosexual,European,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
73267,73268,"I used to be a developer by profession, but no...","Independent contractor, freelancer, or self-em...",Fully remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,Udemy;Pluralsight,16,5,"Developer, front-end;Engineer, data;Engineer, ...",NaN,NaN,Start a free trial;Visit developer communities...,Canada,NaN,NaN,NaN,C#;JavaScript;Lua;PowerShell;SQL;TypeScript,PowerShell;Rust;TypeScript,Microsoft SQL Server;Neo4j;Redis,Neo4j;Redis,Microsoft Azure,AWS;Google Cloud;Microsoft Azure;OpenStack,ASP.NET Core ;Blazor;Node.js;React.js;Svelte,ASP.NET Core ;Node.js;Svelte,Apache Kafka;Apache Spark,NaN,Docker;Kubernetes;npm;Pulumi;Terraform,Docker;Kubernetes;npm;Pulumi;Terraform,Visual Studio;Visual Studio Code,Neovim;Visual Studio Code,Linux-based;Windows,Linux-based;Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Confluence;Jira Work Management;Trello;Wrike,NaN,Microsoft Teams;Slack;Zoom,Slack;Zoom,Favorable,Collectives on Stack Overflow;Stack Overflow;S...,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, somewhat",25-34 years old,Man,No,Straight / Heterosexual,"Or, in your own words:",None of the above,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN

In [65]:
schema_df = pd.read_csv('desktop/pandas/survey_results_schema.csv')
schema_df

,qid,qname,question,force_resp,type,selector
0,QID16,S0,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
1,QID12,MetaInfo,Browser Meta Info,False,Meta,Browser
2,QID1,S1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
3,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
4,QID296,Employment,Which of the following best describes your cur...,False,MC,MAVR
...,...,...,...,...,...,...
74,QID290,Frequency_2,Interacting with people outside of your immedi...,NaN,MC,MAVR
75,QID290,Frequency_3,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR
76,QID294,TrueFalse_1,Are you involved in supporting new hires durin...,NaN,MC,MAVR
77,QID294,TrueFalse_2,Do you use learning resources provided by your...,NaN,MC,MAVR
78,QID294,TrueFalse_3,Does your employer give you time to learn new ...,NaN,MC,MAVR

In [66]:
dict_cream = {'name': ['Brian Michael','Owen Kelly', 'Candy Pange'], 'weekly intake': [5,6,9],'Email':['bri01@gmail.com','owen66@gmail.com','pang02@gmail.com'] ,'favourite car':['Bently','Buggati','Mercedes']}
print(dict_cream)

{'name': ['Brian Michael', 'Owen Kelly', 'Candy Pange'], 'weekly intake': [5, 6, 9], 'Email': ['bri01@gmail.com', 'owen66@gmail.com', 'pang02@gmail.com'], 'favourite car': ['Bently', 'Buggati', 'Mercedes']}

In [67]:
poo

            name  weekly intake favourite car
0  Brian Michael              5        Bently
1     Owen Kelly              6       Buggati
2    Candy Pange              9      Mercedes

In [68]:
poo = pd.DataFrame(dict_cream)
poo

            name  weekly intake             Email favourite car
0  Brian Michael              5   bri01@gmail.com        Bently
1     Owen Kelly              6  owen66@gmail.com       Buggati
2    Candy Pange              9  pang02@gmail.com      Mercedes

In [69]:
dict_cream = {'email':['brimic@gmail.com','owenke@gmail.com','candpa@gmail.com'],'first': ['Brian','Owen', 'Candy'],'last':['Michael', 'Kelly','Pange'], 'weekly intake': [5,6,9], 'favourite car':['Bently','Buggati','Mercedes']}
print(dict_cream)

poo = pd.DataFrame(dict_cream)
poo

{'email': ['brimic@gmail.com', 'owenke@gmail.com', 'candpa@gmail.com'], 'first': ['Brian', 'Owen', 'Candy'], 'last': ['Michael', 'Kelly', 'Pange'], 'weekly intake': [5, 6, 9], 'favourite car': ['Bently', 'Buggati', 'Mercedes']}

              email  first     last  weekly intake favourite car
0  brimic@gmail.com  Brian  Michael              5        Bently
1  owenke@gmail.com   Owen    Kelly              6       Buggati
2  candpa@gmail.com  Candy    Pange              9      Mercedes

In [70]:
poo.append({'first':'Tracy', 'last': 'Akinyi', 'full_name': 'Tracy Akinyi', 'favourite_car': 'Gwagon', 'weekly_intake': 8,'email': 'tracyaki@gmail.com'}, ignore_index = True)

C:\Users\User\AppData\Local\Temp\ipykernel_7284\319749454.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  poo.append({'first':'Tracy', 'last': 'Akinyi', 'full_name': 'Tracy Akinyi', 'favourite_car': 'Gwagon', 'weekly_intake': 8,'email': 'tracyaki@gmail.com'}, ignore_index = True)

,email,first,last,weekly intake,favourite car,favourite_car,full_name,weekly_intake
0,brimic@gmail.com,Brian,Michael,5.0,Bently,NaN,NaN,NaN
1,owenke@gmail.com,Owen,Kelly,6.0,Buggati,NaN,NaN,NaN
2,candpa@gmail.com,Candy,Pange,9.0,Mercedes,NaN,NaN,NaN
3,tracyaki@gmail.com,Tracy,Akinyi,NaN,NaN,Gwagon,Tracy Akinyi,8.0

In [71]:
poo.drop(['favourite_car', 'full_name', 'weekly_intake'], axis=1)

KeyError: "['favourite_car', 'full_name', 'weekly_intake'] not found in axis"

In [72]:
poo

              email  first     last  weekly intake favourite car
0  brimic@gmail.com  Brian  Michael              5        Bently
1  owenke@gmail.com   Owen    Kelly              6       Buggati
2  candpa@gmail.com  Candy    Pange              9      Mercedes

In [73]:
# Starting off

In [74]:
# finding the median salary of a developer

df['CompTotal'].median()

77500.0

In [75]:
# Runing the median function on the entire dataframe
# This finds numerical values in our data and finds their median

df.median()

C:\Users\User\AppData\Local\Temp\ipykernel_7284\3688799262.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.median()

ResponseId                   36634.5
CompTotal                    77500.0
VCHostingPersonal use            NaN
VCHostingProfessional use        NaN
WorkExp                          8.0
ConvertedCompYearly          67845.0
dtype: float64

In [76]:
# To get a broad and statistical overview of your data use(.describe())

df.describe()

,ResponseId,CompTotal,VCHostingPersonal use,VCHostingProfessional use,WorkExp,ConvertedCompYearly
count,73268.000000,3.842200e+04,0.0,0.0,36769.000000,3.807100e+04
mean,36634.500000,2.342434e+52,NaN,NaN,10.242378,1.707613e+05
std,21150.794099,4.591478e+54,NaN,NaN,8.706850,7.814132e+05
min,1.000000,0.000000e+00,NaN,NaN,0.000000,1.000000e+00
25%,18317.750000,3.000000e+04,NaN,NaN,4.000000,3.583200e+04
50%,36634.500000,7.750000e+04,NaN,NaN,8.000000,6.784500e+04
75%,54951.250000,1.540000e+05,NaN,NaN,15.000000,1.200000e+05
max,73268.000000,9.000000e+56,NaN,NaN,50.000000,5.000000e+07

In [77]:
# To find the number of rows that were filled up use(.count())

df['CodingActivities'].count()

58899

In [78]:
# to find the number of people who answered a question(.value_counts())
df['NEWCollabToolsHaveWorkedWith'].value_counts()

Visual Studio Code                                                                                            6753
Visual Studio;Visual Studio Code                                                                              2930
Notepad++;Visual Studio;Visual Studio Code                                                                    1959
Vim;Visual Studio Code                                                                                        1432
IntelliJ;Visual Studio Code                                                                                   1204
                                                                                                              ...
Atom;IntelliJ;IPython/Jupyter;NetBeans;PyCharm;Sublime Text;Vim;Visual Studio;Visual Studio Code                 1
Android Studio;Eclipse;IntelliJ;NetBeans;Notepad++;PhpStorm;Sublime Text;Visual Studio Code;Webstorm;Xcode       1
IntelliJ;Neovim;PyCharm;Vim;Visual Studio;Visual Studio Code;Xcode                                               1
Atom;Eclipse;IntelliJ;IPython/Jupyter;PyCharm;RStudio;Visual Studio;Visual Studio Code                           1
Eclipse;GoLand;Vim;Visual Studio Code                                                                            1
Name: NEWCollabToolsHaveWorkedWith, Length: 15063, dtype: int64

In [79]:
df['DatabaseHaveWorkedWith'].value_counts()

MySQL                                                                3563
PostgreSQL                                                           3519
Microsoft SQL Server                                                 3238
SQLite                                                               2022
MongoDB                                                              1655
                                                                     ...
Elasticsearch;IBM DB2;MongoDB;MySQL                                     1
Cloud Firestore;Microsoft SQL Server;MongoDB;MySQL;Neo4j                1
Cloud Firestore;MongoDB;Oracle;PostgreSQL;Redis;SQLite                  1
MariaDB;Microsoft SQL Server;MySQL;Neo4j;Oracle;PostgreSQL;SQLite       1
Microsoft SQL Server;Neo4j;Redis                                        1
Name: DatabaseHaveWorkedWith, Length: 4223, dtype: int64

## Grouping

In [80]:
## Here we will use the (group by) function

# to group a certain column eg Country column

countrygrp=df.groupby(['Country'])

In [81]:
# how to look at a group of stuff here by country name
# here now every information comes with that country we specified
countrygrp.get_group('Uganda')

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
5371,5372,I am a developer by profession,"Student, full-time",NaN,NaN,"Secondary school (e.g. American high school, G...",Books / Physical media;Other online resources ...,Technical documentation;Written Tutorials;Stac...,NaN,3,NaN,NaN,NaN,NaN,Visit developer communities like Stack Overflo...,Uganda,NaN,NaN,NaN,Python;Rust,Rust,SQLite,SQLite,DigitalOcean,DigitalOcean,Django,Django,NaN,NaN,Docker,Docker,Visual Studio Code,Visual Studio Code,Linux-based,Linux-based,Git,Command-line,NaN,NaN,ClickUp,NaN,Slack,Slack,Favorable,Stack Overflow;Stack Exchange,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,"Yes, somewhat",18-24 years old,Man,No,Straight / Heterosexual,African,None of the above,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
5719,5720,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Fully remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media,NaN,NaN,5,5,"Developer, front-end;Developer, full-stack;Dev...",2 to 9 employees,I have little or no influence,Start a free trial,Uganda,UGX\tUgandan shilling,NaN,NaN,HTML/CSS;Java;JavaScript;Rust;SQL;TypeScript,HTML/CSS;Java;JavaScript;Rust;SQL;TypeScript,PostgreSQL,PostgreSQL,NaN,NaN,Nuxt.js;Vue.js,NaN,NaN,NaN,NaN,NaN,IntelliJ;Visual Studio Code,IntelliJ;Visual Studio Code,macOS,macOS,Git,Code editor;Command-line,NaN,NaN,NaN,NaN,Zoom,Zoom,Unsure,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,Not sure,25-34 years old,Man,No,Straight / Heterosexual,African,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
9376,9377,I am a developer by profession,"Employed, full-time",Full in-person,Hobby;Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Friend or family member;Other online resources...,Technical documentation;Blogs;Written Tutorial...,NaN,4,4,"Developer, full-stack",10 to 19 employees,I have a great deal of influence,Start a free trial;Visit developer communities...,Uganda,UGX\tUgandan shilling,NaN,NaN,HTML/CSS;JavaScript;Python,Go;TypeScript,MariaDB;MySQL;PostgreSQL;Redis;SQLite,Cassandra;MongoDB,Google Cloud;Heroku,DigitalOcean;Linode;VMware,Django;Flask;jQuery,React.js;Vue.js,Flutter;NumPy;Pandas,Scikit-learn,Ansible;Docker;npm;Yarn,NaN,Android Studio;Nano;PyCharm,NaN,Linux-based,Linux-based;Windows;Windows Subsystem for Linu...,Git,Command-line,NaN,NaN,Trello,NaN,Google Chat;Zoom,NaN,Favorable,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Less than once per month or monthly,"Yes, somewhat",25-34 years old,Man,No,Straight / Heterosexual,African,None of the above,None of the above,Yes,Independent contributor,5.0,Strongly agree,Neither agree nor disagree,Strongly disagree,Strongly agree,Strongly agree,Strongly disagree,Neither agree nor disagree,1-2 times a week,Never,Never,15-30 minutes a day,Less than 15 minutes a day,Somewhat long,Innersource initiative,Yes,Yes,Yes,Appropriate in length,Neither easy nor difficult,NaN
9584,9585,I am a developer by profession,"Independent contractor, freelancer, or self-em...","Hybrid (some remote, some in-person)",Hobby;Bootstrapping a business;Freelance/contr...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Blogs;Online books;Video-based Online Courses;...,Coursera;edX;Udacity;Other,8,5,"Engineer, data;Developer, full-stack;Developer...",2 to 9 employees,I have a great deal of influence,Start a free trial;Ask developers I know/work ...,Uganda,USD\tUnited States dollar,NaN,Monthly,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript,MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL;Redis,Firebase;Google Cloud;Heroku;Linode;Managed Ho...,Google Cloud;Linode;Managed Hosting;Microsoft ...,Angular;Flask;Laravel;Node.js,Angular;Flask;Laravel;Next.js;Node.js;React.js,Ionic;NumPy;Pandas;Scikit-learn,Apache Spark;NumPy;Pandas;Scikit-learn,Docker;Homebrew;npm,Docker;Homebrew;npm,Atom;IPython/Jupyter;PhpStorm;PyCharm;Sublime ...,PyCharm;Visual Studio Code;Xcode,Linux-based;macOS,Linux-based;macOS,Git,Command-line,NaN,NaN,Trello,Notion;Trello,Slack;Zoom,Slack;Zoom,Unsure,Collectives on Stack Overflow;Stack Overflow;S...,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,Man,No,Straight / Heterosexual,African,Prefer not to say,None of the above,Yes,Independent contributor,5.0,Agree,Neither agree nor disagree,Strongly disagree,Agree,Agree,Agree,Neither agree nor disagree,1-2 times a week,1-2 times a week,Never,30-60 minutes a day,Less than 15 minutes a day,Somewhat long,Continuous integration (CI) and (more often) c...,No,Yes,No,Too long,Neither easy nor difficult,NaN
13079,13080,I code primarily as a hobby,"Not employed, but looking for work",NaN,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;Video-based Online Courses;Writ...,Coursera,2,NaN,"Developer, front-end;Developer, full-stack",NaN,NaN,Ask developers I know/work with,Uganda,NaN,NaN,NaN,JavaScript;PHP;SQL,JavaScript;PHP;SQL,MySQL,MongoDB;MySQL,NaN,NaN,jQuery;React.js,jQuery;React.js,React Native,React Native,npm;Yarn,npm;Yarn,Visual Studio Code,Visual Studio Code,Windows,Other (please specify):,Git,Command-line,NaN,NaN,NaN,NaN,Zoom,Zoom,Unsure,Stack Overflow,Daily or almost daily,Yes,NaN,Not sure,25-34 years old,Man,No,Straight / Heterosexual,African,"Or, in your own words:",I have an anxiety disorder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67479,67480,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Fully remote,Hobby;Freelance/contract work,Something else,Books / Physical media;Other online resources ...,Technical documentation;Blogs;Stack Overflow;O...,NaN,11,8,"Engineer, site reliability;Developer, full-sta...",2 to 9 employees,I have little or no influence,Start a free trial;Visit developer communities...,Uganda,UGX\tUgandan shilling,150000.0,Weekly,APL;C;C#;HTML/CSS;Java;JavaScript;PHP;SQL,APL;C;C#;HTML/CSS;Java;JavaScript;PHP;SQL,Microsoft SQL Server;MySQL;Oracle,Microsoft SQL Server;MySQL;Oracle,Google Cloud,Google Cloud,Angular.js;ASP.NET;jQuery,Angular.js;ASP.NET;jQuery,.NET;Cordova,.NET;Cordova,NaN,NaN,Android Studio;Notepad++;Visual Studio,Android Studio;Notepad++;Visual Studio,Windows,Windows,I don't use one,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unsure,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,Less than once per month or monthly,"Yes, definitely",25-34 years old,Man,No,Straight / Heterosexual,African,None of the above,None of the above,Yes,Independent contributor,8.0,Neither agree nor disagree,Agree,Neither agree nor disagree,Strongly agree,Strongly agree,Agree,Strongly agree,NaN,NaN,NaN,Over 120 minutes a day,Over 120 minutes a day,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,2050.0
70042,70043,I am a developer by profession,"Independent contractor, freelancer, or self-em...","Hybrid (some remote, some in-person)",Hobby;Contribute to open-source projects;Freel...,Some college/university study without earning ...,Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,NaN,5,Less than 1 year,"Developer, front-end;Developer, full-stack;Edu...","Just me - I am a freelancer, sole proprietor, ...",I have a great deal of influence,Visit developer communities like Stack Overflo...,Uganda,TZS\tTanzanian shilling,NaN,NaN,HTML/CSS;JavaScript;Python,Dart;Go;Kotlin;PHP;Ruby,Cloud Firestore,Cloud Firestore;MongoDB;MySQL;Oracle,Firebase;Google Cloud,AWS;DigitalOcean;Firebase;Google Cloud,Node.js;React.js,Django;Express;Flask;jQuery;Node.js;React.js,Keras;NumPy;Pandas;TensorFlow,Flutter;Keras;NumPy;Pandas;React Native;Tensor...,npm;Unity 3D,npm;Unity 3D,Android Studio;IPython/Jupyter;Notepad++;Visua...,Android Studio;Visual Studio Code,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,NaN,NaN,Favorable,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,Neutral,18-24 years old,Man,No,NaN,African,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
71019,71020,I am a developer by profession,"Not employed, but looking for work;Independent...",Fully remote,Hobby;Contribute to open-source projects,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,edX,8,NaN,"Developer, back-end;DevOps specialist;Develope...",NaN,NaN,Start a free trial;Visit developer communities...,Uganda,NaN,NaN,NaN,Bash/Shell;C;C++;Python;Rust,C;Go;Python;Rust,PostgreSQL;SQLite,PostgreSQL;SQLite,Google Cloud,AWS;Google Cloud;Microsoft Azure,Django;Flask;Vue.js,Flask;React.js;Vue.js,NaN,NaN,NaN,NaN,Neovim;Vim;Visual Studio Code,Neovim;Visual Studio Code,Linux-based,Linux-based,Git,Command-line,NaN,NaN,Trello,NaN,Zoom,Mattermost;Zoom,Very favorable,Stack Overflow;Stack Exchange,Multiple times per day,Yes,A few times per week,"Yes, somewhat",18-24 years old,Man,No,Straight / Heterosexual,African,None of the above,"I have a mood or emotional disorder (e.g., dep...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
72851,72852,I am learning to code,"Student, full-time",NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Coding Bootcamp;Colleague,NaN,NaN,2,NaN,NaN,NaN,NaN,Visit developer communities like Stack Overflo...,Uganda,NaN,NaN,NaN,C;Dart;HTML/CSS;Java,C#;C++;Dart;Go;HTML/CSS;Java;JavaScript;Kotlin...,NaN,NaN,NaN,NaN,NaN,NaN,Flutter,Flutter;NumPy;Pandas;React Native;TensorFlow;T...,NaN,NaN,Android Studio;IntelliJ;IPython/Jupyter;PyChar...,Android Studio;Eclipse;IntelliJ;IPython/Jupyte...,NaN,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,monday.com,Adobe Workfront;Confluence;Microsoft Planner;M...,Zoom,Cisco Webex Teams;Google Chat;Microsoft Teams;...,Favorable,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,I have never participated in Q&A on Stack Over...,"Yes, somewhat",18-24 years old,Man,No,Straight / Heterosexual,African,None of the above,I have an anxiety disorder;I have learning dif...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
73040,73041,I am a developer by profession,"Independent contractor, freelancer, or self-em...","Hybrid (some remote, some in-person)",Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Written Tutorials;Stack Overflow;Online books;...,NaN,8,5,"Developer, full-stack;Project manager",I don’t know,I have a great deal of influence,Other (please specify):;Ask developers I know/...,Uganda,UGX\tUgandan shilling,NaN,Monthly,Dart;HTML/CSS;JavaScript;Kotlin;PHP;SQL;TypeSc...,Dart;HTML/CSS;JavaScript;Kotlin;PHP;Python;SQL...,Cloud Firestore;MySQL;Firebase Realtime Databa...,Cloud Firestore;MariaDB;MySQL;SQLite,Firebase,DigitalOcean;Firebase;Google Cloud;IBM Cloud o...,Angular;Angular.js;jQuery;Laravel;Node.js,Angular;Laravel;Node.js;React.js;Vue.js,Cordova;Flutter;Ionic,Cordova;Flutter;Ionic;React Native,Homebrew;npm,Docker;Homebrew;npm;Yarn,Android Studio;Eclipse;IntelliJ;Notepad++;PhpS...,Android Studio;Eclipse;Notepad++;PhpStorm;Visu...,Linux-based;macOS;Windows,macOS;Windows,Git,Command-line,NaN,NaN,NaN,NaN,Zoom,Microsoft Teams;Zoom,Indifferent,Stack Overflow,Daily or almost daily,Yes,Less than once per month or monthly,Not sure,35-44 years old,Man,"Or, in your own words:",Straight / Heterosexual,African,None of the above,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN

In [82]:
# To find information on a particular column like the gender in uganda
# we can first filter


filt = df['Country']=="Uganda"
df.loc[filt]['Gender'].value_counts()

Man                                                  57
Woman                                                 2
Prefer not to say                                     1
Non-binary, genderqueer, or gender non-conforming     1
Name: Gender, dtype: int64

In [83]:
df['Gender'].value_counts()

Man                                                                                   64607
Woman                                                                                  3399
Prefer not to say                                                                      1172
Non-binary, genderqueer, or gender non-conforming                                       704
Or, in your own words:                                                                  279
Man;Non-binary, genderqueer, or gender non-conforming                                   235
Man;Or, in your own words:                                                              171
Woman;Non-binary, genderqueer, or gender non-conforming                                 160
Man;Woman;Non-binary, genderqueer, or gender non-conforming                              31
Man;Woman                                                                                24
Man;Or, in your own words:;Woman;Non-binary, genderqueer, or gender non-conforming       18
Or, in your own words:;Woman;Non-binary, genderqueer, or gender non-conforming           15
Or, in your own words:;Non-binary, genderqueer, or gender non-conforming                 14
Or, in your own words:;Woman                                                             13
Man;Or, in your own words:;Non-binary, genderqueer, or gender non-conforming              9
Man;Or, in your own words:;Woman                                                          2
Name: Gender, dtype: int64

In [84]:
# To look at the median in a country 

countrygrp['CompTotal'].median()

Country
Afghanistan                                 6000.0
Albania                                     5500.0
Algeria                                    75000.0
Andorra                                    31500.0
Angola                                    600000.0
                                           ...
Venezuela, Bolivarian Republic of...        1094.0
Viet Nam                                15000000.0
Yemen                                      20750.0
Zambia                                      6200.0
Zimbabwe                                     950.0
Name: CompTotal, Length: 180, dtype: float64

In [85]:
 # to see median salary in a specific country
    
countrygrp['CompTotal'].median().loc['Germany']

59000.0

In [86]:
# To see more aggregate functions(.agg)

countrygrp['CompTotal'].agg(['median','mean']).tail(50)

                                                        median          mean
Country
Republic of Moldova                                    12000.0  6.986243e+04
Romania                                                15200.0  3.901268e+04
Russian Federation                                    170000.0  3.854137e+05
Rwanda                                                700000.0  3.764343e+06
Saint Kitts and Nevis                                      NaN           NaN
Saint Lucia                                             2000.0  2.000000e+03
San Marino                                                 NaN           NaN
Saudi Arabia                                           20000.0  1.066029e+06
Senegal                                              3000000.0  5.126143e+06
Serbia                                                 60000.0  1.799524e+05
Seychelles                                              2700.0  2.700000e+03
Sierra Leone                                               NaN           NaN
Singapore                                              11000.0  7.219033e+04
Slovakia                                                3300.0  1.435218e+04
Slovenia                                                4216.5  2.220290e+04
Solomon Islands                                            0.0  0.000000e+00
Somalia                                                12000.0  1.200000e+04
South Africa                                           80000.0  3.115172e+05
South Korea                                         40000000.0  5.140019e+07
Spain                                                  40000.0  4.416284e+04
Sri Lanka                                             180000.0  6.915069e+06
Sudan                                                 180000.0  1.730955e+05
Suriname                                                 800.0  8.000000e+02
Swaziland                                                  0.0  0.000000e+00
Sweden                                                 52000.0  1.704226e+05
Switzerland                                           102000.0  9.991170e+04
Syrian Arab Republic                                    1550.0  2.286907e+05
Taiwan                                                700000.0  1.055883e+07
Tajikistan                                              3500.0  3.950000e+03
Thailand                                               85000.0  1.227580e+07
The former Yugoslav Republic of Macedonia              66000.0  1.791259e+05
Timor-Leste                                             4950.0  4.950000e+03
Togo                                                  175000.0  1.750000e+05
Trinidad and Tobago                                    13800.0  1.615000e+04
Tunisia                                                 2200.0  4.710786e+03
Turkey                                                 18000.0  4.588648e+04
Turkmenistan                                           10000.0  1.830000e+04
Uganda                                               1300000.0  2.420922e+06
Ukraine                                                 7250.0  4.756761e+04
United Arab Emirates                                   20000.0  6.020203e+04
United Kingdom of Great Britain and Northern Ir...     58000.0  6.748744e+04
United Republic of Tanzania                           500000.0  1.255664e+07
United States of America                              140000.0  1.138952e+48
Uruguay                                                64000.0  1.579212e+05
Uzbekistan                                              4250.0  3.454374e+06
Venezuela, Bolivarian Republic of...                    1094.0  4.498590e+03
Viet Nam                                            15000000.0  4.443807e+07
Yemen                                                  20750.0  1.071667e+05
Zambia                                                  6200.0  5.613333e+03
Zimbabwe                                                 950.0  9.445000e+04

In [87]:
# How to know the total number of people who know python

filt = df['Country'] == 'Russian Federation	'
df.loc[filt]['LanguageHaveWorkedWith'].str.contains('python').sum()

0

## Cleraning Data  Casting Datatypes and Handling Missing Values

In [88]:
import numpy as np

In [100]:
people = {
    'First': ['Corey', 'Jane', 'John', 'Chris', ' 0', 'mihjkj', 'NA'],
    'Last' : ['Schafer', 'Doe', 'Doe', 'Kimu', 'husj', 'np.na', 'missing'],
    'Email': ['coreysch@gmail.com', 'janedo@gmail.com','johndoe@gmail.com',' none',' np.nan',' sghs','sgdy'],
    'Age'  : ['33','55','63','36', 'None','None', 'Missing']
}

In [101]:
suu=pd.DataFrame(people)
suu

    First     Last               Email      Age
0   Corey  Schafer  coreysch@gmail.com       33
1    Jane      Doe    janedo@gmail.com       55
2    John      Doe   johndoe@gmail.com       63
3   Chris     Kimu                none       36
4       0     husj              np.nan     None
5  mihjkj    np.na                sghs     None
6      NA  missing                sgdy  Missing

In [103]:
# Dropping values that do not have name,email and age

suu.dropna()
# we do not have an (NA or NaN)

    First     Last               Email      Age
0   Corey  Schafer  coreysch@gmail.com       33
1    Jane      Doe    janedo@gmail.com       55
2    John      Doe   johndoe@gmail.com       63
3   Chris     Kimu                none       36
4       0     husj              np.nan     None
5  mihjkj    np.na                sghs     None
6      NA  missing                sgdy  Missing